### ISSUE TITLE
Python client significantly slower when retrieving query results than Studio

### ISSUE THREAD

**Issue by thomaschristopherking** [vaticle/typedb-client-python#257]
## Description

When running a comparison on getting a single attribute using the python client, compared to Studio, Python is around five times slower.

## Environment

1. TypeDB version: 2.10.0
2. OS of TypeDB server: Windows 11
3. Studio version: 2.10.0-alpha-4
4. OS of Studio: Windows
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:

1. Load the following schema:
```
define
first_name  sub attribute, value string;
```
2. Run the following Python script (providing a suitable db name):

```python

import time
import uuid

from typedb.client import TypeDB, SessionType, TransactionType, TypeDBTransaction

db_name = "<put-db-name-here>"


def create_first_names():
        with TypeDB.core_client("localhost:1729") as client:
            with client.session(db_name, SessionType.DATA) as session:
                with session.transaction(TransactionType.WRITE) as tx:
                    for i in range(50_000):
                        insert_name = f'insert \'{uuid.uuid4()}\' isa first_name;'
                        tx.query().insert(insert_name)
                    tx.commit()


def test_first_name_fetch():
    match_name = 'match $fn isa first_name; get $fn;'
    tx: TypeDBTransaction
    with TypeDB.core_client("localhost:1729") as client:
        with client.session(db_name, SessionType.DATA) as session:
            with session.transaction(TransactionType.READ) as tx:
                start = time.time()
                matches = tx.query().match(match_name)
                for m in matches:
                    name = m.map().get('fn').get_value()
                diff = time.time() - start
                print(f'method_execution_time_seconds: {diff}')
                
                
if __name__ == "__main__":
    create_first_names()
    
    # Executed twice, first time to ensure query plan caching, second is the actual test.
    test_first_name_fetch()
    test_first_name_fetch()
```

3. Compare the runtime to executing the following query in Studio:
`match $fn isa first_name; get $fn;`

## Expected Output

A similar execution time for both Python and Studio queries.

## Actual Output

Python time: ~5.5s
Studio time: ~1.4s to execute, and ~1.972s to output results

**Comment by thomaschristopherking** [comment]
Hi Alex, thanks for looking into this, it makes sense. If it's just for localhost then I guess it's not such a big deal (although I think our network latency is low in the cloud as well). But why does this not occur in Studio?

**Comment by TheDr1ver** [comment]
For what it's worth, just in case it helps with narrowing down the Python speed issues, I've noticed that it takes significantly more time to run a single complex query (e.g., starting with 5 Attributes, find all Entities that have those attributes (maybe 3 matches?), then find all Relations that have those Entities as Players (maybe 5 Relation matches?)) than it does to simply dump every thing in the database and post-process all the results in Python.

If I've got a batch of 800 or so queries (resetting read tx's after every 25 queries run) and I'm watching the log of each query being run in real-time, I've noticed that when it hangs on getting a result, it always seems to hang on the more complex queries rather than the short ones.

My point is, to a certain extent, I think the complexities of a specific search (or maybe a complex search thrown into a batch of searches?) contributes to the slow-down much more significantly than just the act of retrieving all the data.

**Comment by alexjpwalker** [comment]
Absolutely @TheDr1ver - the impact of a client-server connection's inefficiency will be minimal when the query itself is complex to execute on the server. `match $x isa first_name` is one of the simplest queries possible in TypeDB.

Having said that, if your query is significantly slower than dumping the whole DB and post-processing results in Python, that may indicate a query planning issue and may be worth raising in https://github.com/vaticle/typedb. For instance, if retrieving all people with a filter like `match $p isa person, has age $age; $age < 40;` were to perform significantly worse than
```py
[(cm.get("p"), cm.get("a")) for cm in tx.query().match("$p isa person, has age $a;") if cm.get("a").get_value() < 40]
```
then that would certainly indicate a bug in the query planner.

**Comment by alexjpwalker** [comment]
@thomaschristopherking : I believe we've found a conclusive answer to the inefficiency of Client Python (versus Clients Java and Node.js):

https://grpc.io/docs/guides/performance/#python

> Streaming RPCs create extra threads for receiving and possibly sending the messages, which makes **streaming RPCs much slower than unary RPCs** in gRPC Python, unlike the other languages supported by gRPC.

This implies that the behaviour we are seeing (where Python is significantly slower at retrieving query answers than Studio, which uses Client Java) is expected in gRPC Python.

The gRPC team propose one potential fix, which is refactoring the code to use `asyncio`. However, this is a significant undertaking, and with the development of `typedb-client-rust` due to be completed in the fairly near future, we will be rewriting Client Python as a thin Python wrapper over an underlying Rust library - which should run optimally, and resolve this issue.

**Comment by thomaschristopherking** [comment]
Thank you @alexjpwalker that makes sense, another Python annoyance. Guessing this issue could be closed (or linked to the rust client implementation?). I think we can wait for the Rust client.

**Comment by alexjpwalker** [comment]
Absolutely - this issue will now form part of the TypeDB Client Rust Rewrite. Thanks again for flagging this issue up!

**Comment by alexjpwalker** [comment]
Closing this issue as it (should) largely dissolve when we rewrite the Python client to call the Rust client through FFI.
